### ISSUE TITLE
20th Century Wpns -Plus- Reborn for FWE 603-WMK for FWE-Calibrv14-eXcalibrv23

### ISSUE THREAD

**Issue by Kelmych** [loot/fallout3#13]
http://www.nexusmods.com/fallout3/mods/18668

```
name: 20th Century Weapons -Plus- Reborn FWE-WMK-Calibr14_V1_70RC_18668.esp
tag:
  - Names
  - Relev
  - Stats
dirty:
  - crc: 0xDBF185AA
    util: "[FO3Edit](http://www.nexusmods.com/fallout3/mods/637)"
    itm: 474
    udr: 1
```

```
name: 20th_Century_Weapons -Plus- Reborn_v1_70RC-18668_Ironsights_v1_1.esp
tag:
  - Graphics
  - Names
  - Stats
```

```
name: xCALIBR_ammo_Override_v1_01_for_20th Century Weapons -Plus- Reborn FWE-WMK-Calibr14_V1_70RC_18668.esp
dirty:
  - crc: 0x32EAC10D
    util: "[FO3Edit](http://www.nexusmods.com/fallout3/mods/637)"
    itm: 351
    udr: 1
```
