### ISSUE TITLE
Barren Badlands - Dirty Plugin

### ISSUE THREAD

**Issue by MacSplody** [loot/fallout3#130]
### [Barren Badlands](https://www.nexusmods.com/fallout3/mods/21842/)

```yaml
  - name: 'Barren Badlands.esp'
    dirty:
      - <<: *quickClean
        crc: 0x0E203290
        util: '[FO3Edit v4.0.3](https://www.nexusmods.com/fallout3/mods/637)'
        itm: 1
        udr: 50884
```
