### ISSUE TITLE
Better Game Performance - Dirty Plugin

### ISSUE THREAD

**Issue by MacSplody** [loot/fallout3#143]
### [Better Game Performance](https://www.nexusmods.com/fallout3/mods/13520)
Version: Final
```yaml
  - name: 'BetterGamePerformance.esp'
    dirty:
      - <<: *quickClean
        crc: 0x72748F72
        util: '[FO3Edit v4.0.3](https://www.nexusmods.com/fallout3/mods/637)'
        udr: 29115
```
