### ISSUE TITLE
Clutter Remover - Dirty Plugin

### ISSUE THREAD

**Issue by MacSplody** [loot/fallout3#148]
### [Clutter Remover](https://www.nexusmods.com/fallout3/mods/22396)
Version 4.0
```yaml
  - name: 'Clutter Remover.esp'
    dirty:
      - <<: *quickClean
        crc: 0x38F01415
        util: '[FO3Edit v4.0.3](https://www.nexusmods.com/fallout3/mods/637)'
        udr: 4054

  - name: 'Rubble and Litter Remover.esp'
    dirty:
      - <<: *quickClean
        crc: 0xD8155BAF
        util: '[FO3Edit v4.0.3](https://www.nexusmods.com/fallout3/mods/637)'
        udr: 2312
```
