### ISSUE TITLE
Fallout 3 ALL TREES remover - Dirty plugin

### ISSUE THREAD

**Issue by MacSplody** [loot/fallout3#149]
### [Fallout 3 ALL TREES remover](https://www.nexusmods.com/fallout3/mods/23361)
Version 1.00
```yaml
  - name: 'tree.esp'
    dirty:
      - <<: *quickClean
        crc: 0x1B7886C6
        util: '[FO3Edit v4.0.3](https://www.nexusmods.com/fallout3/mods/637)'
        itm: 2
        udr: 55099
```
