### ISSUE TITLE
SpringVale Performance Mod - Dirty plugin

### ISSUE THREAD

**Issue by MacSplody** [loot/fallout3#177]
### [SpringVale Performance Mod](https://www.nexusmods.com/fallout3/mods/22558)
Version: 03 Jun 2017
```yaml
  - name: 'Sprinvale performance.esp'
    dirty:
      - <<: *quickClean
        crc: 0xB03EA5C4
        util: '[FO3Edit v4.0.3](https://www.nexusmods.com/fallout3/mods/637)'
        itm: 1
        udr: 89
```
