### ISSUE TITLE
Blackened - Bash Tags missing

### ISSUE THREAD

**Issue by MacSplody** [loot/fallout3#238]
### [Blackened](https://www.nexusmods.com/fallout3/mods/18173/)

Bash tags will still need to be done as some of the merged patches have tags while the standalone versions do not.

```yaml
  - name: 'Blackened FWE + MMM + EVE + Project Beauty.esp'
    tag:
      - Actors.Stats
      - Factions
      - Invent
      - Names
      - Relev
      - Scripts
      - C.Light
      - C.Music
      - C.Name
      - C.Owner
      - C.Water
```

Some of those tags don't look right, based on what the plugin should cover.

```yaml
  - name: 'Blackened FWE + MMM + Project Beauty.esp'
    tag:
      - Actors.Stats
      - Factions
      - Invent
      - Names
      - Relev
      - Scripts
```

`Blackened EVE + Project Beauty.esp`
`Blackened FWE + EVE.esp`
`Blackened FWE + EVE + Project Beauty.esp`
`Blackened FWE + MMM.esp`
`Blackened FWE + MMM + EVE.esp`
`Blackened FWE + MMM + EVE + Project Beauty.esp`
`Blackened FWE + MMM + Project Beauty.esp`
`Blackened MMM + EVE.esp`

#### Not included in any merged patch
Blackened RH + FWE + EVE.esp

_Originally posted by @MacSplody in https://github.com/loot/fallout3/issues/220#issuecomment-857964162_
