### ISSUE TITLE
WinterizedT51bDX.esp

### ISSUE THREAD

**Issue by Kelmych** [loot/fallout3#31]
http://www.nexusmods.com/fallout3/mods/6167

```
name: WinterizedT51bDX.esp
msg:
  - type: say
    content: 'Use the version from either "Winterized DX-6167.rar" or "DX compatibility-6167.rar"'
tag:
  - Scripts
dirty:
  - crc: 0x1D21BEE9
    util: FO3Edit 3.0.32
    itm: 1
```

```
name: WinterizedT51bDX.esp
msg:
  - type: say
    content: 'Use the version from either "Winterized DX-6167.rar" or "DX compatibility-6167.rar"'
tag:
  - Scripts
dirty:
  - crc: 0xB32FD263
    util: FO3Edit 3.0.32
    itm: 3
```
