### ISSUE TITLE
NotSoFast.esp (A Note Easily Missed)

### ISSUE THREAD

**Issue by Kelmych** [loot/fallout3#33]
http://www.nexusmods.com/fallout3/mods/4730

```
name: NotSoFast.esp
dirty:
  - crc: 0xFFF16D14
    util: FO3Edit 3.0.32
    udr: 29
```
