### ISSUE TITLE
An Evening With Mister Manchester

### ISSUE THREAD

**Issue by Kelmych** [loot/fallout3#34]
http://www.nexusmods.com/fallout3/mods/5630

```
name: HeirApparent.esp
dirty:
  - crc: 0xB633DB19
    util: FO3Edit 3.0.32
    nav: 1
```

```
name: FasterMorePowerfulMines.esp
after:
  - name: The Mantis Imperative - Mantis.esp
tag:
  - Stats
```
