### ISSUE TITLE
ITM report

### ISSUE THREAD

**Issue by IllusiveMan196** [loot/fallout3#355]
- [x] [Skill Books Readable Excerpts](https://www.nexusmods.com/fallout3/mods/19504)
```
  - name: 'ReadBookExcerpts.esp'
    dirty:
      - <<: *quickClean
        crc: 0x2B21F1C9
        util: '[FO3Edit v4.0.3](https://www.nexusmods.com/fallout3/mods/637)'
        itm: 6
        udr: 2
    clean:
      - crc: 0x578DA64C
        util: 'FO3Edit v4.0.3'
```
- [x] [Add all DLC items to test room](https://www.nexusmods.com/fallout3/mods/24872)
```
  - name: 'ALLDLCITEMSINTESTQA.esp'
    dirty:
      - <<: *quickClean
        crc: 0xD7652C4E
        util: '[FO3Edit v4.0.3](https://www.nexusmods.com/fallout3/mods/637)'
        itm: 1
    clean:
      - crc: 0x07FCBE1F
        util: 'FO3Edit v4.0.3'
```
- [x] [Fairfax City Interiors](https://www.nexusmods.com/fallout3/mods/23611)
```
  - name: 'Fairfax City Interiors.esp'
    dirty:
      - <<: *quickClean
        crc: 0x1BE2F237
        util: '[FO3Edit v4.0.3](https://www.nexusmods.com/fallout3/mods/637)'
        itm: 6
    clean:
      - crc: 0x2AE84242
        util: 'FO3Edit v4.0.3'
```
- [x] [What Happens in Fish Hunters Village (helpfully named FHVF3PL.esp)](https://www.nexusmods.com/fallout3/mods/24770)
```
  - name: 'FHVF3PL.esp'
    dirty:
      - <<: *quickClean
        crc: 0xA9EE5C6C
        util: '[FO3Edit v4.0.3](https://www.nexusmods.com/fallout3/mods/637)'
        itm: 185
        udr: 29
    clean:
      - crc: 0x275BAC13
        util: 'FO3Edit v4.0.3'
```
- [x] [Realistic Wasteland and Lighting (GOTY version)](https://www.nexusmods.com/fallout3/mods/20346)
```
  - name: 'FO3 RWL GOTY.esp'
    dirty:
      - <<: *quickClean
        crc: 0x20480DE7
        util: '[FO3Edit v4.0.3](https://www.nexusmods.com/fallout3/mods/637)'
        itm: 6
    clean:
      - crc: 0x014ED5B5
        util: 'FO3Edit v4.0.3'
```
- [x] [FO3 Better Messages](https://www.nexusmods.com/fallout3/mods/24833)
```
  - name: 'FO3BetterMessagesAllDLC.esp'
    dirty:
      - <<: *quickClean
        crc: 0x01111E51
        util: '[FO3Edit v4.0.3](https://www.nexusmods.com/fallout3/mods/637)'
        itm: 7
    clean:
      - crc: 0xEC0C74D9
        util: 'FO3Edit v4.0.3'
```
- [x] [New Vegas-style food mechanics](https://www.nexusmods.com/fallout3/mods/24477)
```
  - name: 'Fallout3-NVFoodMechanics-DLC-1.0.esp'
    dirty:
      - <<: *quickClean
        crc: 0x411AC911
        util: '[FO3Edit v4.0.3](https://www.nexusmods.com/fallout3/mods/637)'
        itm: 4
    clean:
      - crc: 0x3D6830E1
        util: 'FO3Edit v4.0.3'
```

**Comment by IllusiveMan196** [comment]
[New Vegas-style food mechanics](https://www.nexusmods.com/fallout3/mods/24477)
```
  - name: 'Fallout3-NVFoodMechanics-DLC-1.0.esp'
    dirty:
      - <<: *quickClean
        crc: 0x411AC911
        util: '[FO3Edit v4.0.3](https://www.nexusmods.com/fallout3/mods/637)'
        itm: 4
    clean:
      - crc: 0x3D6830E1
        util: 'FO3Edit v4.0.3'
```

**Comment by IllusiveMan196** [comment]
- [x] [There's No Such Thing As Bad Publicity (Quest)](https://www.nexusmods.com/fallout3/mods/24940)

```
  - name: 'There's No Such Thing As Bad Publicity.esp'
    dirty:
      - <<: *quickClean
        crc: 0x88F835EE
        util: '[FO3Edit v4.0.3](https://www.nexusmods.com/fallout3/mods/637)'
        itm: 37
        udr: 1
    clean:
      - crc: 0xA7BA305C
        util: 'FO3Edit v4.0.3'
```
