### ISSUE TITLE
In the Shadow of the Swamp

### ISSUE THREAD

**Issue by Kelmych** [loot/fallout3#36]
http://www.nexusmods.com/fallout3/mods/7268

```
name: PLFewerItems.esp   CRC: E3EF4366   ITM:1  UDR:56  Bash Tags: Delev, Relev
tag:
  - Delev
  - Relev
dirty:
  - crc: 0xE3EF4366
    util: FO3Edit 3.0.32
    itm: 1
    udr: 56
```

``````
 either have it load after``` FO3 Wanderers Edition - DLC Point Lookout.esp'``` or use priorities
``````

Similarly
`PLweightadjust.esp`  should load before FO3 Wanderers Edition - DLC Point Lookout.esp or priorities should also be used for this plugin. What do you suggest?
