### ISSUE TITLE
Existence2.0.esp (Existence 2_0 - Robot Radio)

### ISSUE THREAD

**Issue by Kelmych** [loot/fallout3#38]
http://www.nexusmods.com/fallout3/mods/5612

```
name: Existence2.0.esp
dirty:
  - crc: 0x0E5309DA
  - util: FO3Edit 3.0.32
  - nav: 1
```
