### ISSUE TITLE
CALIBRv14 Ammunition Schematics for FWE-WMK-CRAFT-V1_3-18639.esp (Ammunition Schematics for FWE-WMK-CRAFT-Full CalibrV1_4)

### ISSUE THREAD

**Issue by Kelmych** [loot/fallout3#42]
http://www.nexusmods.com/fallout3/mods/18639

```
name: CALIBRv14 Ammunition Schematics for FWE-WMK-CRAFT-V1_3-18639.esp
dirty:
  - crc: 0x9AB2CF5E
    util: FO3Edit 3.0.32
    itm: 2
```
