### ISSUE TITLE
DelayDLC

### ISSUE THREAD

**Issue by Kelmych** [loot/fallout3#48]
http://www.nexusmods.com/fallout3/mods/5253

```
name: delaysteel.esp
after:
  - name: FO3 Wanderers Edition - DLC Broken Steel.esp
tag:
  - Scripts
dirty:
  - crc: 0xE818B262
    util: FO3Edit 3.0.32
    itm: 1
```

```
name: delaypl.esp
after:
  - name: FO3 Wanderers Edition - DLC Point Lookout.esp
dirty:
  - crc: 0xD5DAF34E
    util: FO3Edit 3.0.32
    itm: 2
```

```
name: delayzeta.esp
tag:
  - Scripts
dirty:
  - crc: 0x776851A3
    util: FO3Edit 3.0.32
    itm: 2
```

```
name: Delay ThePitt + Anchorage.esp
tag:
  - Scripts
```
