### ISSUE TITLE
ArefuExpandedByAzar.esm (The Crimson Caravan)

### ISSUE THREAD

**Issue by Kelmych** [loot/fallout3#49]
http://www.nexusmods.com/fallout3/mods/12466

```
name: ArefuExpandedByAzar.esm
tag:
  - Invent
  - Relations
dirty:
  - crc: 0x81581FCA
    util: FO3Edit 3.0.32
    itm: 209
    udr: 54
    nav: 16
```
