### ISSUE TITLE
Fixes for Crimson Caravan

### ISSUE THREAD

**Issue by Kelmych** [loot/fallout3#50]
http://www.nexusmods.com/fallout3/mods/15686

```
name: ArefuExpandedByAzar-FixMisc.esp
dirty:
  - crc: 0x283EAF75
    util: FO3Edit 3.0.32
    itm: 6
```

```
name: ArefuExpandedByAzar-FixOptAddNew.esp
dirty:
  - crc: 0x9B1EFE6B
    util: FO3Edit 3.0.32
    itm: 4
```

```
name: ArefuExpandedByAzar-FixOptRemOld.esp
dirty:
  - crc: 0x675E86E8
    util: FO3Edit 3.0.32
    udr: 39
```
