### ISSUE TITLE
Temple of the Union Overhaul.esp

### ISSUE THREAD

**Issue by Kelmych** [loot/fallout3#51]
http://www.nexusmods.com/fallout3/mods/19242

```
name: Temple of the Union Overhaul.esp
dirty:
  - crc: 0xE4A3C388
    util: FO3Edit 3.0.32
    itm: 34
    udr: 167
```
