### ISSUE TITLE
Canterbury Commons Overhaul

### ISSUE THREAD

**Issue by Kelmych** [loot/fallout3#52]
http://www.nexusmods.com/fallout3/mods/13301

```
name: Canterbury Commons Interiors Embiggened.esp
inc:
  - name: Canterbury Commons Interiors Embiggened.esm
msg:
  - type: say
    content: 'Use only Canterbury Commons plugin'
    condition: file("Canterbury Commons Interiors Embiggened.esm")
dirty:
  - crc: 0x3D8ABED8
    util: FO3Edit 3.0.32
    itm: 181
    udr: 20
    nav: 3
tag:
  - Relations
```

```
name: Canterbury Commons Interiors Embiggened.esm
inc:
  - name: Canterbury Commons Interiors Embiggened.esp
msg:
  - type: say
    content: 'Use only Canterbury Commons plugin'
    condition: file("Canterbury Commons Interiors Embiggened.esp")
dirty:
  - crc: 0x43E23B19
    util: FO3Edit 3.0.32
    itm: 181
    udr: 20
    nav: 3
tag:
  - Relations
```
