### ISSUE TITLE
Bornagain Zeta Combat Armor Texture Patch.esp

### ISSUE THREAD

**Issue by Kelmych** [loot/fallout3#55]
http://www.nexusmods.com/fallout3/mods/18220

```
name: Bornagain Zeta Combat Armor Texture Patch.esp
dirty:
  - crc: 0xab095a45
    util: FO3Edit 3.0.32
    itm: 2
```
