### ISSUE TITLE
UrgeWashingtonBoS.esp

### ISSUE THREAD

**Issue by Kelmych** [loot/fallout3#56]
http://www.nexusmods.com/fallout3/mods/17939

```
name: UrgeWashingtonBoS.esp
dirty:
  - crc: 0x98fd9bed
    util: FO3Edit 3.0.32
    itm: 14
    udr: 16
```
