### ISSUE TITLE
Vault 101 Revisited.esm

### ISSUE THREAD

**Issue by Kelmych** [loot/fallout3#57]
http://www.nexusmods.com/fallout3/mods/13308

```
name: Vault 101 Revisited.esm
dirty:
  - crc: 0x848d8679
    util: FO3Edit 3.0.32
    itm: 33
    udr: 9
    nav: 2
```
