### ISSUE TITLE
Big Town Overhaul

### ISSUE THREAD

**Issue by Kelmych** [loot/fallout3#59]
http://www.nexusmods.com/fallout3/mods/13229

```
name: Big Town Overhaul [GangStore].esp
dirty:
  - crc: 0x563db400
    util: FO3Edit 3.0.32
    itm: 53
    udr: 684

name: Big Town Overhaul.esp
dirty:
  - crc: 31E2D0E2
    util: FO3Edit 3.0.32
    itm: 41
    udr: 684
```

Only one of these should be used.(see below)
