### ISSUE TITLE
FO3 Wanderers Edition - Main File.esp

### ISSUE THREAD

**Issue by Kelmych** [loot/fallout3#62]
http://www.nexusmods.com/fallout3/mods/2761

```
name: FO3 Wanderers Edition - Main File.esp
after:
  - name: FasterMorePowerfulMines.esp
    condition: file("HeirApparent.esp")
  - name: GlowingGhouls.esp
  - name: The Mantis Imperative - Mantis.esp
```
