### ISSUE TITLE
Creature Companion Fixes

### ISSUE THREAD

**Issue by Kelmych** [loot/fallout3#63]
http://www.nexusmods.com/fallout3/mods/20549

```
name: Creature Companion Fixes.esp
inc:
  - name: Creature Companion Fixes No DLC.esp
msg:
  - type: say
    content: 'Use only Creature Companion Fixes plugin'
    condition: file("Creature Companion Fixes No DLC.esp")
```

```
name: Creature Companion Fixes No DLC.esp
inc:
  - name: Creature Companion Fixes.esp
msg:
  - type: say
    content: 'Use only Creature Companion Fixes plugin'
    condition: file("Creature Companion Fixes.esp")
```
