### ISSUE TITLE
Robco Certified

### ISSUE THREAD

**Issue by Kelmych** [loot/fallout3#66]
http://www.nexusmods.com/fallout3/mods/712

```
name: RobCo Certified v2 FWE.esp
dirty:
  - crc: 0x285ef04
    util: FO3Edit 3.0.32
    itm: 1
```

```
name: RobCo Certified v2.esm
req:
  - name: ..\fose_loader.exe
    display: "[FOSE](http://fose.silverlock.org/)"
dirty:
  - crc: 0xe363b7d7
    util: FO3Edit 3.0.32
    itm: 9
```

```
name: Companion Core.esm
dirty:
  - crc: 0x6f02e35
    util: FO3Edit 3.0.32
    itm: 2
```

```
name: RobCo Certified v2 Zeta Addon.esp
dirty:
  - crc: 0x7e827a3
    util: FO3Edit 3.0.32
    itm: 2
```

```
name: Companion Core DLC Addon.esp
dirty:
  - crc: 0x37145cc8
    util: FO3Edit 3.0.32
    itm: 1
```

```
name: RobcoCertified24SideMod.esp
dirty:
  - crc: 0x9c938fce
    util: FO3Edit 3.0.32
    itm: 2
```

Bash tag data later
