### ISSUE TITLE
RockopolisRebuilt.esp

### ISSUE THREAD

**Issue by Kelmych** [loot/fallout3#67]
http://www.nexusmods.com/fallout3/mods/8769

```
name: RockopolisRebuilt.esp
dirty:
  - crc: 0x51c3dd7a
    util: FO3Edit 3.0.32
    itm: 4
```

Bash tags, if any, later
