### ISSUE TITLE
KDS Zealotlees ACR with Ironsights

### ISSUE THREAD

**Issue by Kelmych** [loot/fallout3#68]
http://www.nexusmods.com/fallout3/mods/17748

```
name: ZL-ACR.esp
tag:
  - Stats
dirty:
  - crc: 0x373C0213
    util: FO3Edit 3.0.32
    itm: 7
```

Different version of same plugin used by Zealotlees ACR mod
