### ISSUE TITLE
KDS Zealotlees MP5 Pack with Ironsights

### ISSUE THREAD

**Issue by Kelmych** [loot/fallout3#69]
http://www.nexusmods.com/fallout3/mods/17749

```
name: ZL-MP5 Pack.esp
dirty:
  - crc: 0xCD453EE7
    util: FO3Edit 3.0.32
    itm: 6
```

Different version of same plugin used by Zealotlees MP5 Pack mod
