### ISSUE TITLE
DriveableMotorCycle.esp

### ISSUE THREAD

**Issue by Kelmych** [loot/fallout3#72]
http://www.nexusmods.com/fallout3/mods/6005

```
name: DriveableMotorCycle.esp
dirty:
  - crc: 0x949faf2c
    util: FO3Edit 3.0.32
    itm: 3
```
