### ISSUE TITLE
FWE - Required Load after rules to match recommended order

### ISSUE THREAD

**Issue by MacSplody** [loot/fallout3#83]
Taken from
[FWE - Combat Overhaul v2_01 (Test ver.alpha)](https://www.nexusmods.com/fallout3/mods/15578)
and
[FWE - FO3 Wanderers Edition](https://www.nexusmods.com/fallout3/mods/2761)
Description pages

Groups not enough to match the suggested order.

Edit: Update rules to remove any that have been implemented with afters or groups.
The original full list of rules can be viewed below. https://github.com/loot/fallout3/issues/83#issuecomment-526023888

```yaml
groups:
  - name: 'eve'
    after:
      - WeaponModKits
  - name: 'default'
  - name: 'WeaponModKits'
    after:
      - FO3 Wanderers Edition
  - name: 'FO3 Wanderers Edition'
    after:
      - RH IronSights
  - name: 'RH IronSights'
  - name: 'FWE - Combat Overhaul_Equipment'
    after:
      - FO3 Wanderers Edition
  - name: 'Mart''s Mutant Mod'
    after:
      - eve
      - FWE - Combat Overhaul_Equipment
```

![image](https://user-images.githubusercontent.com/1944639/111573729-fa605100-87a2-11eb-9bea-502802ac2cb6.png)

```yaml
plugins:
  - name: 'FO3 Wanderers Edition - Main File.esm'
    after:
      - 'Project Beauty.esm'
      - 'RH_IRONSIGHTS.esm'
  - name: 'FO3 Wanderers Edition - Optional Restore Tracers.esp'
    group: 'FO3 Wanderers Edition'
  - name: 'FO3 Wanderers Edition - Optional VATS Realtime.esp'
    group: 'FO3 Wanderers Edition'
  - name: 'FWE - Combat Overhaul_Core.esm'
    after:
      - 'FO3 Wanderers Edition - Main File.esm'
  - name: 'FWE - Combat Overhaul_Equipment.esp'
    group: 'FWE - Combat Overhaul_Equipment'
    after:
      - 'FO3 Wanderers Edition - Followers Enhanced (BrokenSteel).esp'
      - 'FO3 Wanderers Edition - Followers Enhanced.esp'
  - name: 'Mart''s Mutant Mod - DLC Anchorage.esp'
    group: 'Mart''s Mutant Mod'
  - name: 'Mart''s Mutant Mod - DLC Broken Steel.esp'
    group: 'Mart''s Mutant Mod'
  - name: 'Mart''s Mutant Mod - DLC Point Lookout.esp'
    group: 'Mart''s Mutant Mod'
  - name: 'Mart''s Mutant Mod - DLC The Pitt.esp'
    group: 'Mart''s Mutant Mod'
  - name: 'Mart''s Mutant Mod - DLC Zeta.esp'
    group: 'Mart''s Mutant Mod'
  - name: 'Mart''s Mutant Mod - Master Menu Module.esp'
    group: 'Mart''s Mutant Mod'
  - name: 'Mart''s Mutant Mod.esm'
    after:
      - 'FWE - Combat Overhaul_Core.esm'
  - name: 'Mart''s Mutant Mod.esp'
    group: 'Mart''s Mutant Mod'
  - name: 'RH_IRONSIGHTS.esm'
    after:
      - 'Project Beauty.esm'
  - name: 'RH_IronSights_Pitt_NewRifleSights.esp'
    group: 'RH IronSights'
  - name: 'RH_IronSights_PL_NewItems.esp'
    group: 'RH IronSights'
  - name: 'RH_IronSights_RemoveReticule.esp'
    group: 'RH IronSights'
  - name: 'WeaponModKits.esp'
    group: 'WeaponModKits'
  - name: 'WMKAA12Shotgun.esp'
    group: 'WeaponModKits'
```

---

#### Simplify groups

```yaml
groups:
  - name: 'EVE'
    after:
      - WMK
  - name: 'default'
  - name: 'WMK'
    after:
      - FWE
  - name: 'FWE'
    after:
      - RHIS
  - name: 'RHIS'
  - name: 'MMM'
    after:
      - EVE
```

![image](https://user-images.githubusercontent.com/1944639/111574538-950d5f80-87a4-11eb-8ce9-36ab59260f8f.png)

```yaml
plugins:
  - name: 'FO3 Wanderers Edition - Main File.esm'
    group: 'FWE'
  - name: 'FWE - Combat Overhaul_Equipment.esp'
    group: 'FWE'
  - name: 'Mart''s Mutant Mod.esm'
    group: 'MMM'
  - name: 'Mart''s Mutant Mod.esp'
    group: 'MMM'
  - name: 'RH_IRONSIGHTS.esm'
    group: 'RHIS'
  - name: 'WeaponModKits.esp'
    group: 'WMK'
```

**Comment by CptMcSplody** [comment]
Load Order
The following is a suggested load order for using FWE with art's Mutant Mod (MMM), Weapon Mod Kits (WMK), Energy Visuals Enhanced (EVE), and Project Beauty (PB):
---------------------------------------------------- OFFICIAL MASTERS
Fallout3.esm
Anchorage.esm
ThePitt.esm
BrokenSteel.esm
PointLookout.esm
Zeta.esm

---------------------------------------------------- MOD RESOURCES
CRAFT.esm
CALIBR.esm
Project Beauty.esm

<--------------------------------------------------- .esms from all other mods (except follower and weather mods!)
---------------------------------------------------- MOD MASTERS (In this order!)
FO3 Wanderers Edition - Main File.esm
Mart's Mutant Mod.esm
<--------------------------------------------------- .esms from Follower and Weather mods

DarNifiedUIF3.esp
CRAFT - Activation Perk.esp
Project Beauty- Broken Steel.esp
Project Beauty- Point Lookout.esp

<--------------------------------------------------- .esps from all other mods (except follower and weather mods!)
---------------------------------------------------- Fallout Wanderers Edition
FO3 Wanderers Edition - Main File.esp
FO3 Wanderers Edition - DLC Anchorage.esp
FO3 Wanderers Edition - DLC The Pitt.esp
FO3 Wanderers Edition - DLC Broken Steel.esp
FO3 Wanderers Edition - DLC Point Lookout.esp
FO3 Wanderers Edition - DLC Mothership Zeta.esp

FO3 Wanderers Edition - Alternate Travel.esp
FO3 Wanderers Edition - Followers Enhanced.esp (Choose BS OR Non-BS Version)
FO3 Wanderers Edition - OTHER OPTIONAL FWE MODULES
FO3 Wanderers Edition - Project Beauty.esp (FROM FOIP)
FO3 Wanderers Edition - Project Beauty (Followers Enhanced).esp (FROM FOIP)

---------------------------------------------------- Weapon Mod Kits
WeaponModKits.esp

WeaponModKits - FWE Master Release.esp (FROM FOIP)
WeaponModKits - FWE Optional Worn Weapons.esp (FROM FOIP, if using FWE's Worn Weapons)
WeaponModKits - OperationAnchorage.esp (FROM FOIP)
WeaponModKits - ThePitt.esp (FROM FOIP)
WeaponModKits - BrokenSteel.esp (FROM FOIP)
WeaponModKits - PointLookout.esp (FROM FOIP)
WeaponModKits - Zeta.esp (FROM FOIP)

---------------------------------------------------- Energy Visuals Enhanced
EVE.esp
EVE Operation Anchorage.esp

EVE - FWE Master Release.esp  (FROM FOIP)
EVE - FWE Master Release (Followers Enhanced).esp  (FROM FOIP)
EVE Anchorage - FWE DLC Anchorage.esp (FROM FOIP)
EVE - FWE with WeaponModKits.esp  (FROM FOIP)


---------------------------------------------------- Mart's Mutant Mod
Mart's Mutant Mod.esp
Mart's Mutant Mod - DLC Anchorage.esp
Mart's Mutant Mod - DLC The Pitt.esp
Mart's Mutant Mod - DLC Broken Steel.esp
Mart's Mutant Mod - DLC Point Lookout.esp
Mart's Mutant Mod - DLC Zeta.esp

Mart's Mutant Mod - Project Beauty.esp (FROM PROJECT BEAUTY)
Mart's Mutant Mod - FWE Master Release.esp (FROM FOIP)
Mart's Mutant Mod - Project Beauty + FWE.esp (FROM FOIP)

<--------------------------------------------------- Follower and weather mods

Your Merged Patch from FO3Edit.esp

**Comment by MacSplody** [comment]
Taken from
[FWE - Combat Overhaul v2_01 (Test ver.alpha)](https://www.nexusmods.com/fallout3/mods/15578)
and
[FWE - FO3 Wanderers Edition](https://www.nexusmods.com/fallout3/mods/2761)
Description pages

Groups not enough to match the suggested order.

```yaml
groups:
  - name: 'eve'
    after:
      - WeaponModKits
  - name: 'default'
  - name: 'WeaponModKits'
    after:
      - FO3 Wanderers Edition
  - name: 'FO3 Wanderers Edition'
    after:
      - RH IronSights
  - name: 'RH IronSights'
  - name: 'FWE - Combat Overhaul_Equipment'
    after:
      - FO3 Wanderers Edition
  - name: 'Mart''s Mutant Mod'
    after:
      - eve
      - FWE - Combat Overhaul_Equipment
plugins:
  - name: 'CALIBR.esm'
    after:
      - 'CRAFT.esm'
  - name: 'FO3 Wanderers Edition - DLC Broken Steel.esp'
    after:
      - 'FO3 Wanderers Edition - DLC Anchorage.esp'
      - 'FO3 Wanderers Edition - DLC The Pitt.esp'
  - name: 'FO3 Wanderers Edition - DLC Mothership Zeta.esp'
    after:
      - 'FO3 Wanderers Edition - DLC Anchorage.esp'
      - 'FO3 Wanderers Edition - DLC Broken Steel.esp'
      - 'FO3 Wanderers Edition - DLC Point Lookout.esp'
      - 'FO3 Wanderers Edition - DLC The Pitt.esp'
  - name: 'FO3 Wanderers Edition - DLC Point Lookout.esp'
    after:
      - 'FO3 Wanderers Edition - DLC Anchorage.esp'
      - 'FO3 Wanderers Edition - DLC Broken Steel.esp'
      - 'FO3 Wanderers Edition - DLC The Pitt.esp'
  - name: 'FO3 Wanderers Edition - DLC The Pitt.esp'
    after:
      - 'FO3 Wanderers Edition - DLC Anchorage.esp'
  - name: 'FO3 Wanderers Edition - Followers Enhanced (BrokenSteel).esp'
    after:
      - 'FO3 Wanderers Edition - DLC Anchorage.esp'
      - 'FO3 Wanderers Edition - DLC Broken Steel.esp'
      - 'FO3 Wanderers Edition - DLC Mothership Zeta.esp'
      - 'FO3 Wanderers Edition - DLC Point Lookout.esp'
      - 'FO3 Wanderers Edition - DLC The Pitt.esp'
  - name: 'FO3 Wanderers Edition - Main File.esm'
    after:
      - 'Project Beauty.esm'
      - 'RH_IRONSIGHTS.esm'
  - name: 'FO3 Wanderers Edition - Main File.esp'
    after:
      - 'Project Beauty- Broken Steel.esp'
      - 'Project Beauty- Point Lookout.esp'
      - 'RH_IronSights_Basic_AnchoragePlugin.esp'
      - 'RH_IronSights_Basic_BrokenSteelPlugin.esp'
      - 'RH_IronSights_Basic_PittPlugin.esp'
      - 'RH_IronSights_Basic_PointLookoutPlugin.esp'
      - 'RH_IronSights_Basic_VanillaPlugin.esp'
      - 'RH_IronSights_Basic_ZetaPlugin.esp'
  - name: 'FO3 Wanderers Edition - Optional Restore Tracers.esp'
    group: 'FO3 Wanderers Edition'
  - name: 'FO3 Wanderers Edition - Optional VATS Realtime.esp'
    group: 'FO3 Wanderers Edition'
  - name: 'FWE - Combat Overhaul_Core.esm'
    after:
      - 'FO3 Wanderers Edition - Main File.esm'
  - name: 'FWE - Combat Overhaul_Equipment.esp'
    group: 'FWE - Combat Overhaul_Equipment'
    after:
      - 'FO3 Wanderers Edition - DLC Anchorage.esp'
      - 'FO3 Wanderers Edition - DLC Broken Steel.esp'
      - 'FO3 Wanderers Edition - DLC Mothership Zeta.esp'
      - 'FO3 Wanderers Edition - DLC Point Lookout.esp'
      - 'FO3 Wanderers Edition - DLC The Pitt.esp'
      - 'FO3 Wanderers Edition - Followers Enhanced (BrokenSteel).esp'
      - 'FO3 Wanderers Edition - Followers Enhanced.esp'
      - 'Project Beauty- Broken Steel.esp'
      - 'Project Beauty- Point Lookout.esp'
  - name: 'Mart''s Mutant Mod - DLC Anchorage.esp'
    group: 'Mart''s Mutant Mod'
    after:
      - 'Mart''s Mutant Mod.esp'
  - name: 'Mart''s Mutant Mod - DLC Broken Steel.esp'
    group: 'Mart''s Mutant Mod'
    after:
      - 'Mart''s Mutant Mod - DLC Anchorage.esp'
  - name: 'Mart''s Mutant Mod - DLC Point Lookout.esp'
    group: 'Mart''s Mutant Mod'
    after:
      - 'Mart''s Mutant Mod - DLC Anchorage.esp'
      - 'Mart''s Mutant Mod - DLC Broken Steel.esp'
      - 'Mart''s Mutant Mod - DLC The Pitt.esp'
      - 'Mart''s Mutant Mod.esp'
  - name: 'Mart''s Mutant Mod - DLC The Pitt.esp'
    group: 'Mart''s Mutant Mod'
    after:
      - 'Mart''s Mutant Mod - DLC Anchorage.esp'
  - name: 'Mart''s Mutant Mod - DLC Zeta.esp'
    group: 'Mart''s Mutant Mod'
    after:
      - 'Mart''s Mutant Mod - DLC Anchorage.esp'
      - 'Mart''s Mutant Mod - DLC Broken Steel.esp'
      - 'Mart''s Mutant Mod - DLC The Pitt.esp'
  - name: 'Mart''s Mutant Mod - Master Menu Module.esp'
    group: 'Mart''s Mutant Mod'
    after:
      - 'Mart''s Mutant Mod - DLC Anchorage.esp'
      - 'Mart''s Mutant Mod - DLC Broken Steel.esp'
      - 'Mart''s Mutant Mod - DLC Point Lookout.esp'
      - 'Mart''s Mutant Mod - DLC The Pitt.esp'
      - 'Mart''s Mutant Mod - DLC Zeta.esp'
      - 'Mart''s Mutant Mod.esp'
  - name: 'Mart''s Mutant Mod.esm'
    after:
      - 'FWE - Combat Overhaul_Core.esm'
  - name: 'Mart''s Mutant Mod.esp'
    group: 'Mart''s Mutant Mod'
    after:
      - 'Project Beauty- Broken Steel.esp'
      - 'Project Beauty- Point Lookout.esp'
  - name: 'Project Beauty.esm'
    after:
      - 'CALIBR.esm'
      - 'CRAFT.esm'
  - name: 'RH_IRONSIGHTS.esm'
    after:
      - 'Project Beauty.esm'
  - name: 'RH_IronSights_Basic_AnchoragePlugin.esp'
    after:
      - 'Project Beauty- Broken Steel.esp'
      - 'Project Beauty- Point Lookout.esp'
      - 'RH_IronSights_Basic_VanillaPlugin.esp'
  - name: 'RH_IronSights_Basic_BrokenSteelPlugin.esp'
    after:
      - 'Project Beauty- Broken Steel.esp'
      - 'Project Beauty- Point Lookout.esp'
      - 'RH_IronSights_Basic_AnchoragePlugin.esp'
      - 'RH_IronSights_Basic_PittPlugin.esp'
      - 'RH_IronSights_Basic_VanillaPlugin.esp'
  - name: 'RH_IronSights_Basic_PittPlugin.esp'
    after:
      - 'Project Beauty- Broken Steel.esp'
      - 'Project Beauty- Point Lookout.esp'
      - 'RH_IronSights_Basic_AnchoragePlugin.esp'
      - 'RH_IronSights_Basic_VanillaPlugin.esp'
  - name: 'RH_IronSights_Basic_PointLookoutPlugin.esp'
    after:
      - 'Project Beauty- Broken Steel.esp'
      - 'Project Beauty- Point Lookout.esp'
      - 'RH_IronSights_Basic_AnchoragePlugin.esp'
      - 'RH_IronSights_Basic_BrokenSteelPlugin.esp'
      - 'RH_IronSights_Basic_PittPlugin.esp'
      - 'RH_IronSights_Basic_VanillaPlugin.esp'
  - name: 'RH_IronSights_Basic_VanillaPlugin.esp'
    after:
      - 'DarNifiedUIF3.esp'
      - 'Project Beauty- Broken Steel.esp'
      - 'Project Beauty- Point Lookout.esp'
  - name: 'RH_IronSights_Basic_ZetaPlugin.esp'
    after:
      - 'RH_IronSights_Basic_AnchoragePlugin.esp'
      - 'RH_IronSights_Basic_BrokenSteelPlugin.esp'
      - 'RH_IronSights_Basic_PittPlugin.esp'
      - 'RH_IronSights_Basic_PointLookoutPlugin.esp'
      - 'RH_IronSights_Basic_VanillaPlugin.esp'
  - name: 'RH_IronSights_Pitt_NewRifleSights.esp'
    group: 'RH IronSights'
  - name: 'RH_IronSights_PL_NewItems.esp'
    group: 'RH IronSights'
  - name: 'RH_IronSights_RemoveReticule.esp'
    group: 'RH IronSights'
  - name: 'WeaponModKits.esp'
    group: 'WeaponModKits'
  - name: 'WMKAA12Shotgun.esp'
    group: 'WeaponModKits'
```

---
Taken from FWE Readme

Load Order
The following is a suggested load order for using FWE with:
Mart's Mutant Mod (MMM)
Weapon Mod Kits (WMK)
Energy Visuals Enhanced (EVE)
Project Beauty (PB)

### OFFICIAL MASTERS
Fallout3.esm
Anchorage.esm
ThePitt.esm
BrokenSteel.esm
PointLookout.esm
Zeta.esm

### MOD RESOURCES
CRAFT.esm
CALIBR.esm
Project Beauty.esm

###### .esms from all other mods (except follower and weather mods!)

### MOD MASTERS (In this order!)
FO3 Wanderers Edition - Main File.esm
Mart's Mutant Mod.esm
###### .esms from Follower and Weather mods

DarNifiedUIF3.esp
CRAFT - Activation Perk.esp
Project Beauty- Broken Steel.esp
Project Beauty- Point Lookout.esp

###### .esps from all other mods (except follower and weather mods!)

### Fallout Wanderers Edition
FO3 Wanderers Edition - Main File.esp
FO3 Wanderers Edition - DLC Anchorage.esp
FO3 Wanderers Edition - DLC The Pitt.esp
FO3 Wanderers Edition - DLC Broken Steel.esp
FO3 Wanderers Edition - DLC Point Lookout.esp
FO3 Wanderers Edition - DLC Mothership Zeta.esp

FO3 Wanderers Edition - Alternate Travel.esp
FO3 Wanderers Edition - Followers Enhanced.esp (Choose BS OR Non-BS Version)
FO3 Wanderers Edition - OTHER OPTIONAL FWE MODULES
FO3 Wanderers Edition - Project Beauty.esp (FROM FOIP)
FO3 Wanderers Edition - Project Beauty (Followers Enhanced).esp (FROM FOIP)

### Weapon Mod Kits
WeaponModKits.esp

WeaponModKits - FWE Master Release.esp (FROM FOIP)
WeaponModKits - FWE Optional Worn Weapons.esp (FROM FOIP, if using FWE's Worn Weapons)
WeaponModKits - OperationAnchorage.esp (FROM FOIP)
WeaponModKits - ThePitt.esp (FROM FOIP)
WeaponModKits - BrokenSteel.esp (FROM FOIP)
WeaponModKits - PointLookout.esp (FROM FOIP)
WeaponModKits - Zeta.esp (FROM FOIP)

### Energy Visuals Enhanced
EVE.esp
EVE Operation Anchorage.esp

EVE - FWE Master Release.esp  (FROM FOIP)
EVE - FWE Master Release (Followers Enhanced).esp  (FROM FOIP)
EVE Anchorage - FWE DLC Anchorage.esp (FROM FOIP)
EVE - FWE with WeaponModKits.esp  (FROM FOIP)


### Mart's Mutant Mod
Mart's Mutant Mod.esp
Mart's Mutant Mod - DLC Anchorage.esp
Mart's Mutant Mod - DLC The Pitt.esp
Mart's Mutant Mod - DLC Broken Steel.esp
Mart's Mutant Mod - DLC Point Lookout.esp
Mart's Mutant Mod - DLC Zeta.esp

Mart's Mutant Mod - Project Beauty.esp (FROM PROJECT BEAUTY)
Mart's Mutant Mod - FWE Master Release.esp (FROM FOIP)
Mart's Mutant Mod - Project Beauty + FWE.esp (FROM FOIP)

### Follower and weather mods

Your Merged Patch from FO3Edit.esp
