### ISSUE TITLE
Userlist from Clear & Present Danger (Fallout 3) modding guide

### ISSUE THREAD

**Issue by MacSplody** [loot/fallout3#84]
[Clear and Present Danger - A guide for modding Fallout 3](http://wiki.step-project.com/User:Kelmych/Fallout3)

```
plugins:
  - name: '(TWPC) 20CWRECW-WMK-RIFWC-UUF3P-FWE Patch.esp'
    after:
      - 'Bashed Patch, 0.esp'
  - name: '(TWPC) BBB-UUF3P-FWE Patch.esp'
    after:
      - 'Bashed Patch, 0.esp'
  - name: '(TWPC) BFO-MMM-EVE-UUF3P-FWE Patch.esp'
    after:
      - '(TWPC) DIFF3-RI-EVE-MMM-WMK-PRA-F3HMG-F3HF-20CWRE-IMPACT-UUF3P-FWE Patch.esp  '
      - 'Bashed Patch, 0.esp'
  - name: '(TWPC) BRCC-PB Patch.esp'
    after:
      - 'Bashed Patch, 0.esp'
  - name: '(TWPC) BVR-FWE Patch.esp'
    after:
      - 'Bashed Patch, 0.esp'
  - name: '(TWPC) CMRP-FWE Patch.esp'
    after:
      - 'Bashed Patch, 0.esp'
  - name: '(TWPC) DIFF3-RI-EVE-MMM-WMK-PRA-F3HMG-F3HF-20CWRE-IMPACT-UUF3P-FWE Patch.esp'
    after:
      - '(TWPC) 20CWRECW-WMK-RIFWC-UUF3P-FWE Patch.esp'
      - '(TWPC) BFO-MMM-EVE-UUF3P-FWE Patch.esp'
      - '(TWPC) WD-DIFF3-UUF3P-FWE Patch.esp'
      - 'Bashed Patch, 0.esp'
  - name: '(TWPC) GE-UUF3P Patch.esp'
    after:
      - 'Bashed Patch, 0.esp'
  - name: '(TWPC) K9B-MMM-UUF3P-FWE Patch.esp'
    after:
      - 'Bashed Patch, 0.esp'
  - name: '(TWPC) PLR-UUF3P-ISS Patch.esp'
    after:
      - 'Bashed Patch, 0.esp'
  - name: '(TWPC) RIL-UUF3P-DM Patch.esp'
    after:
      - 'Bashed Patch, 0.esp'
  - name: '(TWPC) RRE-PB-FWE Patch.esp'
    after:
      - 'Bashed Patch, 0.esp'
  - name: '(TWPC) TMI-FWE Patch.esp'
    after:
      - 'Bashed Patch, 0.esp'
  - name: '(TWPC) WD-DIFF3-UUF3P-FWE Patch.esp'
    after:
      - '(TWPC) DIFF3-RI-EVE-MMM-WMK-PRA-F3HMG-F3HF-20CWRE-IMPACT-UUF3P-FWE Patch.esp  '
      - 'Bashed Patch, 0.esp'
  - name: '20th Century Weapons -Plus- Reborn FWE-WMK-Calibr14_V1_70RC_18668.esp'
    tag:
      - Invent
      - Scripts
  - name: '20th_Century_Weapons -Plus- Reborn_v1_70RC-18668_Ironsights_v1_1.esp'
    tag:
      - Scripts
  - name: 'ArefuExpandedByAzar-FixMisc.esp'
    tag:
      - Graphics
  - name: 'ArefuExpandedByAzar.esm'
    tag:
      - Relations
  - name: 'Armor Repair Kits PL - FO3.esp'
    tag:
      - Invent
  - name: 'BaileysCrossingMetro.esp'
    dirty:
      - crc: 0xe297ef4b
        util: 'FO3Edit 3.0.32'
        itm: 9
  - name: 'Blackened FWE + MMM + EVE + Project Beauty.esp'
    after:
      - 'Impact.esp'
      - 'UUF3P - FWE Patch.esp'
      - 'WeaponModKits - FWE Master Release.esp'
    tag:
      - C.Light
      - C.Music
      - C.Name
      - C.Owner
      - C.Water
  - name: 'Blackened FWE + MMM + Project Beauty.esp'
    after:
      - 'UUF3P - FWE Patch.esp'
    req:
      - 'FO3 Wanderers Edition - Main File.esp'
  - name: 'Blackened RH + FWE + EVE.esp'
    after:
      - 'Blackened FWE + MMM + EVE + Project Beauty.esp'
  - name: 'blackrock_shooter.esp'
    dirty:
      - crc: 0x448e4ca4
        util: 'FO3Edit 3.0.32'
        itm: 1
    url:
      - 'http://www.nexusmods.com/fallout3/mods/9633'
  - name: 'Brahmin Dairy Products.esp'
    tag:
      - Invent
  - name: 'CALIBRv14 Ammunition Schematics for FWE-WMK-CRAFT-V1_3-18639.esp'
    tag:
      - Scripts
      - Stats
  - name: 'CanterburyCommonsInteriors.esp'
    dirty:
      - crc: 0x3030f941
        util: 'FO3Edit 3.0.32'
        itm: 2
        nav: 1
  - name: 'Caravan Merchants Heal After Combat.esp'
    tag:
      - Actors.Stats
  - name: 'ClearAndPresentAdjustment-GreatOldOnes.esp'
    after:
      - 'Bashed Patch, 0.esp'
  - name: 'ClearAndPresentAdjustment_Beauty_Weapons_2.esp'
    after:
      - 'Bashed Patch, 0.esp'
  - name: 'Confessor Cromwell has a Break_EV.esp'
    tag:
      - Graphics
  - name: 'CPD_Ingestible_Patch.esp'
    after:
      - 'Bashed Patch, 0.esp'
  - name: 'DCInt_ARoomWithAView.esp'
    dirty:
      - crc: 0xd9eb1a7c
        util: 'FO3Edit 3.0.32'
        itm: 121
  - name: 'Dragonskin Tactical Outfit.esp'
    tag:
      - Stats
  - name: 'Dragonskin_for_FWE_2014.esp'
    tag:
      - Stats
    url:
      - 'http://www.nexusmods.com/fallout3/mods/20874'
  - name: 'FO3 Wanderers Edition - DLC Anchorage.esp'
    tag:
      - Graphics
      - Stats
  - name: 'FO3 Wanderers Edition - DLC Mothership Zeta.esp'
    tag:
      - Destructible
      - Graphics
      - Names
      - Stats
  - name: 'FO3 Wanderers Edition - Main File.esp'
    after:
      - 'FasterMorePowerfulMines.esp'
      - 'GlowingGhouls.esp'
      - 'The Mantis Imperative - Mantis.esp'
  - name: 'Fo3HirezdFlamer.esp'
    tag:
      - Graphics
      - Stats
    url:
      - 'http://www.nexusmods.com/fallout3/mods/19931'
  - name: 'Fo3HirezdMinigun.esp'
    tag:
      - Graphics
    url:
      - 'http://www.nexusmods.com/fallout3/mods/19931'
  - name: 'FWEAlienWorkBenchFix.esp'
    dirty:
      - crc: 0xcb9512c4
        util: 'FO3Edit 3.1.1'
        itm: 8
    url:
      - 'http://www.nexusmods.com/fallout3/mods/18234'
  - name: 'Hi-Res Weapons & Ammo Textures.esp'
    tag:
      - Graphics
  - name: 'lexx_brahmin-variant-Fo3.esp'
    dirty:
      - crc: 0xa6f26ec7
        util: 'FO3Edit 3.1.1'
        udr: 8
    url:
      - 'http://www.nexusmods.com/fallout3/mods/21308'
  - name: 'Mart''s Mutant Mod.esp'
    tag:
      - Actors.ACBS
      - Factions
      - Invent
      - Relations
      - Scripts
  - name: 'MetroCars.esp'
    dirty:
      - crc: 0x5f89a907
        util: 'FO3Edit 3.0.32'
        itm: 77
        udr: 4
    url:
      - 'http://www.nexusmods.com/fallout3/mods/19988'
  - name: 'MoreMapMarkers.esp'
    dirty:
      - crc: 0xb7f1fa75
        util: 'FO3Edit 3.0.32'
        itm: 289
        udr: 1
    url:
      - 'http://www.nexusmods.com/fallout3/mods/2446'
  - name: 'Mothership Crew.esm'
    dirty:
      - crc: 0x7b4cd2c6
        util: 'FO3Edit 3.1.1'
        itm: 1
        udr: 14
    url:
      - 'http://www.nexusmods.com/fallout3/mods/8747'
  - name: 'PLweightadjust.esp'
    after:
      - 'Another Interior Mod.esp'
  - name: 'PotomacSteamworks.esp'
    dirty:
      - crc: 0xf705d620
        util: 'FO3Edit 3.1.1'
        itm: 5
    url:
      - 'http://www.nexusmods.com/fallout3/mods/20843'
  - name: 'Powered Power Armor.esp'
    tag:
      - Actors.AIData
      - Stats
  - name: 'PPA - FWE.esp'
    tag:
      - Delev
  - name: 'Refugee Clothing.esp'
    dirty:
      - crc: 0x9c5a8e8b
        util: 'FO3Edit 3.0.32'
        itm: 1
    url:
      - 'http://www.nexusmods.com/fallout3/mods/5580'
  - name: 'RH_WMK_Bridge.esp'
    after:
      - 'WMK Uniques for FWE_EVE Addon.esp'
  - name: 'RubblePilesFix.esp'
    tag:
      - Graphics
    url:
      - 'http://www.nexusmods.com/fallout3/mods/12056'
  - name: 'T3_leather armors.esp'
    tag:
      - graphics
  - name: 'Tattered_suits.esp'
    dirty:
      - crc: 0xc5589397
        util: 'FO3Edit 3.0.32'
        itm: 1
    url:
      - 'http://www.nexusmods.com/fallout3/mods/9167'
  - name: 'The Mantis Imperative - Jello.esp'
    tag:
      - Invent
  - name: 'The Mantis Imperative - Nasty Zeta No Scaling.esp'
    tag:
      - Relev
  - name: 'The Mantis Imperative - Nasty Zeta.esp'
    tag:
      - -Actors.ACBS
      - -C.Encounter
      - -C.Name
      - -Delev
      - -Destructible
      - -Graphics
      - -Invent
      - -Relev
      - -Scripts
      - -Stats
  - name: 'UF3P - Exotic Caravans.esm'
    tag:
      - Invent
  - name: 'UF3P - Exotic Caravans.esp'
    after:
      - 'FO3 Wanderers Edition - Main File.esp'
  - name: 'UUF3P - FWE Patch.esp'
    after:
      - 'delaypl.esp'
      - 'FO3 Wanderers Edition - Main File.esp'
    tag:
      - Actors.ACBS
      - Actors.AIData
      - Actors.Stats
      - Delev
      - Destructible
      - Graphics
      - Names
      - Relations
      - Relev
  - name: 'Weapon Mods Patch.esp'
    after:
      - 'Bashed Patch, 0.esp'
  - name: 'WeaponModKits - BrokenSteel.esp'
    tag:
      - Graphics
      - Stats
    url:
      - 'http://www.nexusmods.com/fallout3/mods/3388'
  - name: 'WeaponModKits - FWE Master Release.esp'
    tag:
      - Stats
  - name: 'WeaponModKits - Zeta.esp'
    tag:
      - Stats
    url:
      - 'http://www.nexusmods.com/fallout3/mods/3388'
  - name: 'xCALIBR_ammo_Override_v1_01_for_20th Century Weapons -Plus- Reborn FWE-WMK-Calibr14_V1_70RC_18668.esp'
    tag:
      - Destructible
      - Names
      - Stats
  - name: 'Xepha''s Dynamic Weather - Main + DLC Merged.esp'
    priority: 127
  - name: 'ZL-MP5 Pack.esp'
    dirty:
      - crc: 0xcd453ee7
        util: 'FO3Edit 3.0.32'
        itm: 6
    url:
      - 'http://www.nexusmods.com/fallout3/mods/17749'
```
